admin_homepage:
    path:     /dashboard
    defaults: { _controller: AdminBundle:Home:index }
    
admin_user_list:
    path:     /users/list/{page}
    defaults: { _controller: AdminBundle:User:index, page:1 }
admin_user_insert_batch:
    path:     /users/insert
    defaults: { _controller: AdminBundle:User:insert }

admin_user_show:
    path:     /users/show/{userId}
    defaults: { _controller: AdminBundle:User:show }

