admin_homepage:
    path:     /dashboard
    defaults: { _controller: AdminBundle:Home:index }
    
admin_user_list:
    path:     /users/list/{page}
    defaults: { _controller: AdminBundle:User:index, page:1 }
admin_user_insert_batch:
    path:     /users/insert
    defaults: { _controller: AdminBundle:User:insert }


