services:
#    admin.example:
#        class: AdminBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
services:
    user.service.class:
        class: AdminBundle\Services\UserService
        arguments: [ @doctrine.orm.entity_manager ]