AdminBundle\Entity\Category:
    type: entity
    table: null
    repositoryClass: AdminBundle\Entity\CategoryRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: '100'
        slug:
            type: string
            length: '255'
        description:
            type: text
    oneToMany:
        products:
            targetEntity: Product
            mappedBy: category
    lifecycleCallbacks: {  }
