AdminBundle\Entity\Post:
    type: entity
    table: post
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        title:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        content:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: ''
        userId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: user_id
        createdDate:
            type: datetime
            nullable: false
            comment: ''
            column: created_date
        updatedDate:
            type: datetime
            nullable: false
            comment: ''
            column: updated_date
    lifecycleCallbacks: {  }
