AdminBundle\Entity\User:
    type: entity
    table: null
    repositoryClass: AdminBundle\Entity\UserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        username:
            type: string
            length: '100'
        password:
            type: string
            length: '255'
        email:
            type: string
            length: '100'
        firstname:
            type: string
            length: '64'
        lastname:
            type: string
            length: '64'
        active:
            type: integer
        role:
            type: integer
        createdDate:
            type: datetimetz
            column: created_date
        updatedDate:
            type: datetimetz
            column: updated_date
    lifecycleCallbacks: {  }
