AdminBundle\Entity\User:
    type: entity
    table: user
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        username:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
        firstname:
            type: string
            nullable: false
            length: 64
            fixed: false
            comment: ''
        lastname:
            type: string
            nullable: false
            length: 64
            fixed: false
            comment: ''
        password:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        email:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
        role:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
        createdDate:
            type: datetime
            nullable: false
            comment: ''
            column: created_date
        updatedDate:
            type: datetime
            nullable: false
            comment: ''
            column: updated_date
    lifecycleCallbacks: {  }
